services:
  redis:
    image: redis:7
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/usr/src/app
      - ./catalog:/usr/src/catalog:ro
      - ~/.aws:/root/.aws:ro
    env_file:
      - .env
    environment:
      AWS_PROFILE: ${AWS_PROFILE}
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    command: celery -A app.workers.celery_app:celery_app worker -l INFO
    volumes:
      - ./app:/usr/src/app
      - ./catalog:/usr/src/catalog:ro
      - ~/.aws:/root/.aws:ro
    env_file:
      - .env
    environment:
      AWS_PROFILE: ${AWS_PROFILE}
    depends_on:
      - redis
    restart: unless-stopped
